name: Receive repository dispatch event
on:
  repository_dispatch:
    types: [dispatch-event]
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
    - name: checking out source trigger code
      uses: actions/checkout@v2
      with: 
        repository: ${{ github.event.client_payload.repository }} 
        ref: ${{ github.event.client_payload.branch }} 
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: source-repo
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'  # Specify the Go version you want to use
    - name: checking out local code
      uses: actions/checkout@v2
      with:
        path: target-repo
    - name: Run Go Checks
      uses: ../target-repo/.github/actions/go-checks

