name: Trigger repository dispatch event
on: push
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository dispatch
        run: |
          curl -X POST https://api.github.com/repos/swethareddy-kalwakuntla/Go-Github/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -u ${{ secrets.PERSONAL_ACCESS_TOKEN }} \
          --data '{"event_type": "dispatch-event", "client_payload": {}}'
