name: Go Checks

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        path: source-repo
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'  # Specify the Go version you want to use
    - name: Run Go Checks
      uses: ./.github/actions/go-checks
